openapi: 3.0.0
info:
  title: Price Monitor
  version: 1.0.0
  description: API documentation for the Price Monitor application

servers:
  - url: http://localhost:8000/api/
    description: Local development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        email_verified_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Source:
      type: object
      properties:
        id:
          type: integer
        url:
          type: string
        name:
          type: string
        email:
          type: string
        price:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        201:
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Bad request

  /login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        401:
          description: Unauthorized

  /logout:
    post:
      summary: Logout the authenticated user
      security:
        - bearerAuth: []
      responses:
        200:
          description: User logged out successfully
        401:
          description: Unauthorized

  /auth-user:
    get:
      summary: Get authenticated user details
      security:
        - bearerAuth: []
      responses:
        200:
          description: Authenticated user details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        401:
          description: Unauthorized

  /source:
    get:
      summary: Get a list of subscriptions for the authenticated user
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of subscriptions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Source'
        401:
          description: Unauthorized

    post:
      summary: Create a new subscription
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Source'
      responses:
        201:
          description: Subscription created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'
        400:
          description: Bad request
        401:
          description: Unauthorized

    delete:
      summary: Delete a task
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: task
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Task deleted successfully
        401:
          description: Unauthorized
        403:
          description: Forbidden

